from Scripts.LHZ import build_extended_lhz_array
from Scripts.Spanning_lines import (
    build_lhz_faces,
    canonical_state,
    labels_from_state,
    is_valid_spanning_line_coords,
    right_moving_face_crossings,
    cnot_steps_from_moves,
    cnot_gate_list_from_steps,
)

def qaoa_up_number_of_spanning_lines(n):
    """
    Return the number of spanning lines required for the all-to-all QAOA
    problem unitary U_P.

    The problem Hamiltonian is

        H_P = sum_{j<k} J_jk Z_j Z_k + sum_j h_j Z_j.

    The spanning-line schedule must expose all two-body Z parities.

    The number of U_P spanning lines is

        floor(n/2) + 1.

    Therefore:
        - for odd n, e.g. n=5, there are 3 lines;
        - for even n, e.g. n=6, there are 4 lines.

    Parameters
    ----------
    n : int
        Number of logical qubits.

    Returns
    -------
    int
        Number of U_P spanning lines.
    """
    if n < 2:
        raise ValueError("n must be at least 2.")

    return n // 2 + 1

def initial_qaoa_up_zigzag_spanning_line(n, grid):
    """
    Construct the initial zig-zag spanning line for the QAOA problem unitary U_P.

    The line starts from the node carrying label (0,) in row 0. It then moves
    alternately south-west and south-east, using the horizontal periodic
    boundary condition of the extended LHZ architecture.

    For n=5, this produces the label line

        [(0,), (0, 4), (1, 4), (1, 3), (2, 3)].

    Parameters
    ----------
    n : int
        Number of logical qubits.

    grid : np.ndarray
        Extended LHZ grid.

    Returns
    -------
    tuple
        Coordinate representation of the initial U_P spanning line.
    """
    width = grid.shape[1]

    state = tuple(
        (row, 0 if row % 2 == 0 else width - 1)
        for row in range(n)
    )

    state = canonical_state(state, grid)

    if not is_valid_spanning_line_coords(list(state), grid):
        raise ValueError(
            "The initial U_P zig-zag line is not a valid spanning line."
        )

    return state


def choose_compatible_right_moves_for_qaoa_up(state, moves, grid):
    """
    Choose a maximal deterministic set of compatible right-moving face crossings
    for the QAOA problem-unitary U_P schedule.

    A set of moves is compatible if applying the moves still gives a valid
    top-to-bottom spanning line. Candidate moves are considered in increasing
    row order, and at most one move is accepted per row.

    Parameters
    ----------
    state : tuple
        Current coordinate spanning line.

    moves : list[dict]
        Candidate right-moving moves returned by right_moving_face_crossings.

    grid : np.ndarray
        Extended LHZ grid.

    Returns
    -------
    chosen_moves : list[dict]
        Compatible moves selected from the candidate list.

    new_state : tuple
        Updated coordinate spanning line.
    """
    if not moves:
        return [], state

    moves_by_row = {}

    for move in moves:
        row = move["row"]

        if row not in moves_by_row:
            moves_by_row[row] = move

    candidate_state = list(state)
    chosen_moves = []

    for row in sorted(moves_by_row):
        move = moves_by_row[row]

        trial_state = list(candidate_state)
        trial_state[row] = move["new_coord"]
        trial_state = canonical_state(tuple(trial_state), grid)

        if is_valid_spanning_line_coords(list(trial_state), grid):
            candidate_state = list(trial_state)
            chosen_moves.append(move)

    new_state = canonical_state(tuple(candidate_state), grid)

    return chosen_moves, new_state


def advance_qaoa_up_spanning_line_right(
    state,
    grid,
    faces,
    num_right_updates=2,
):
    """
    Advance a U_P spanning line by a specified number of right-moving updates.

    For the QAOA problem unitary U_P, each new spanning line is generated by
    applying two global right-moving update steps. Each update consists of:

      1. finding all currently allowed right-moving face crossings;
      2. selecting a compatible set of such crossings;
      3. applying them simultaneously.

    Parameters
    ----------
    state : tuple
        Current coordinate spanning line.

    grid : np.ndarray
        Extended LHZ grid.

    faces : list[dict]
        Local LHZ faces returned by build_lhz_faces.

    num_right_updates : int
        Number of global right-moving update steps to apply. For U_P this
        should normally be 2.

    Returns
    -------
    new_state : tuple
        Updated coordinate spanning line.

    chosen_moves_all : list[dict]
        Flattened list of all selected moves.

    cnot_steps_all : list[dict]
        Flattened CNOT-step metadata associated with the selected moves.

    cnot_gates_all : list[list]
        Flattened CNOT gate list in the format
        ["CNOT", [control, target], "N/A"].
    """
    if num_right_updates < 1:
        raise ValueError("num_right_updates must be at least 1.")

    current_state = state
    chosen_moves_all = []
    cnot_steps_all = []
    cnot_gates_all = []

    for _ in range(num_right_updates):
        moves = right_moving_face_crossings(current_state, grid, faces)

        chosen_moves, new_state = choose_compatible_right_moves_for_qaoa_up(
            current_state,
            moves,
            grid,
        )

        if not chosen_moves:
            raise RuntimeError(
                "No compatible right-moving face crossings were found while "
                "generating the U_P spanning-line schedule.\n"
                f"Current labels: {labels_from_state(current_state, grid)}\n"
                f"Current coords: {current_state}"
            )

        cnot_steps = cnot_steps_from_moves(chosen_moves)
        cnot_gates = cnot_gate_list_from_steps(cnot_steps)

        chosen_moves_all.extend(chosen_moves)
        cnot_steps_all.extend(cnot_steps)
        cnot_gates_all.extend(cnot_gates)

        current_state = new_state

    return current_state, chosen_moves_all, cnot_steps_all, cnot_gates_all


def generate_qaoa_up_lhz_spanning_lines(
    n,
    max_steps=None,
    return_coords=False,
    return_cnot_steps=False,
    verbose=False,
):
    """
    Generate the LHZ spanning-line schedule for the QAOA problem unitary U_P.

    The problem unitary is

        U_P(gamma) = exp(i gamma H_P),

    with

        H_P = sum_{j<k} J_jk Z_j Z_k + sum_j h_j Z_j.

    The schedule is designed to expose all two-body Z parities Z_j Z_k as
    local physical Z rotations on at least one spanning line.

    Rules
    -----
    1. The initial line is a periodic zig-zag line starting from label (0,).

    2. For odd n, every transition between consecutive U_P spanning lines is
       generated by two global right-moving updates through the extended LHZ
       architecture.

    3. For even n, every transition is generated by two global right-moving
       updates except the final transition, which is generated by only one
       global right-moving update.

    4. The number of U_P spanning lines is

           floor(n/2) + 1.

    Examples
    --------
    For n=5, the schedule is

        [(0,),   (0, 4), (1, 4), (1, 3), (2, 3)]
        [(0, 1), (1,),   (2,),   (2, 4), (3, 4)]
        [(1, 2), (0, 2), (0, 3), (3,),   (4,)]

    Parameters
    ----------
    n : int
        Number of logical qubits.

    max_steps : int or None
        Optional maximum number of right-moving update steps. If None, a
        conservative default is used.

    return_coords : bool
        If True, return both label lines and coordinate lines.

    return_cnot_steps : bool
        If True, return a dictionary containing label lines, coordinate lines,
        move metadata, CNOT metadata, and grid/faces.

    verbose : bool
        If True, print the generated U_P label lines.

    Returns
    -------
    list or tuple or dict
        If return_cnot_steps=False and return_coords=False, returns only the
        list of label spanning lines.

        If return_coords=True, returns

            (label_lines, coord_lines).

        If return_cnot_steps=True, returns a dictionary with keys:
            "unitary",
            "label_lines",
            "coord_lines",
            "step_moves",
            "cnot_steps_by_update",
            "cnot_gates_by_update",
            "grid",
            "faces".
    """
    if n < 2:
        raise ValueError("n must be at least 2.")

    grid = build_extended_lhz_array(n)
    faces = build_lhz_faces(grid)

    num_lines = qaoa_up_number_of_spanning_lines(n)

    if max_steps is None:
        max_steps = 4 * n * (n + 1)

    current_state = initial_qaoa_up_zigzag_spanning_line(n, grid)

    coord_lines = [current_state]
    label_lines = [labels_from_state(current_state, grid)]

    step_moves = []
    cnot_steps_by_update = []
    cnot_gates_by_update = []

    if verbose:
        print("U_P step 0:", label_lines[-1])

    right_updates_used = 0

    for line_index in range(1, num_lines):
        is_final_transition = line_index == num_lines - 1

        # Odd n: all transitions are double jumps.
        # Even n: the final transition is only a single jump.
        if n % 2 == 0 and is_final_transition:
            num_right_updates = 1
        else:
            num_right_updates = 2

        if right_updates_used + num_right_updates > max_steps:
            raise RuntimeError(
                "Maximum number of right-moving updates reached before "
                "generating all U_P spanning lines."
            )

        (
            current_state,
            chosen_moves,
            cnot_steps,
            cnot_gates,
        ) = advance_qaoa_up_spanning_line_right(
            current_state,
            grid,
            faces,
            num_right_updates=num_right_updates,
        )

        right_updates_used += num_right_updates

        coord_lines.append(current_state)
        label_lines.append(labels_from_state(current_state, grid))

        step_moves.append(chosen_moves)
        cnot_steps_by_update.append(cnot_steps)
        cnot_gates_by_update.append(cnot_gates)

        if verbose:
            print(
                f"U_P step {line_index}:",
                label_lines[-1],
                f"(right updates: {num_right_updates})",
            )

    final_last_label = label_lines[-1][-1]

    if final_last_label != (n - 1,):
        raise RuntimeError(
            "U_P spanning-line generation failed the final-label sanity check.\n"
            f"Expected final last label: {(n - 1,)}\n"
            f"Actual final last label:   {final_last_label}\n"
            f"Final U_P spanning line:   {label_lines[-1]}"
        )

    if return_cnot_steps:
        return {
            "unitary": "U_P",
            "label_lines": label_lines,
            "coord_lines": coord_lines,
            "step_moves": step_moves,
            "cnot_steps_by_update": cnot_steps_by_update,
            "cnot_gates_by_update": cnot_gates_by_update,
            "grid": grid,
            "faces": faces,
        }

    if return_coords:
        return label_lines, coord_lines

    return label_lines


def generate_qaoa_ux_lhz_spanning_lines(
    n,
    up_spanning_data=None,
    return_coords=False,
    return_cnot_steps=False,
    verbose=False,
):
    """
    Generate the LHZ spanning-line data for the QAOA mixer unitary U_X.

    The mixer unitary is

        U_X(beta) = exp(i beta sum_j X_j).

    Unlike U_P, the intermediate movements required to localize RX rotations
    do not follow the standard right-moving extended-LHZ sweep. These movements
    should be handled separately by the U_X compiler.

    Therefore, this function only returns the initial and final spanning line
    for U_X. Both are taken to be the final spanning line of the U_P schedule.

    For n=5, this line is

        [(1, 2), (0, 2), (0, 3), (3,), (4,)].

    Parameters
    ----------
    n : int
        Number of logical qubits.

    up_spanning_data : dict or None
        Optional output of generate_qaoa_up_lhz_spanning_lines(...,
        return_cnot_steps=True). If None, it is generated automatically.

    return_coords : bool
        If True, return both label lines and coordinate lines.

    return_cnot_steps : bool
        If True, return a dictionary. The CNOT lists are empty because this
        function does not generate the internal U_X movements.

    verbose : bool
        If True, print the U_X initial/final line.

    Returns
    -------
    list or tuple or dict
        If return_cnot_steps=False and return_coords=False, returns the U_X
        label lines.

        If return_coords=True, returns

            (label_lines, coord_lines).

        If return_cnot_steps=True, returns a dictionary with:
            "unitary",
            "label_lines",
            "coord_lines",
            "step_moves",
            "cnot_steps_by_update",
            "cnot_gates_by_update",
            "grid",
            "faces".
    """
    if up_spanning_data is None:
        up_spanning_data = generate_qaoa_up_lhz_spanning_lines(
            n,
            return_cnot_steps=True,
            verbose=False,
        )

    up_label_lines = up_spanning_data["label_lines"]
    up_coord_lines = up_spanning_data["coord_lines"]

    if not up_label_lines or not up_coord_lines:
        raise ValueError("The supplied U_P spanning data contains no lines.")

    ux_label_line = up_label_lines[-1]
    ux_coord_line = up_coord_lines[-1]

    label_lines = [ux_label_line]
    coord_lines = [ux_coord_line]

    if verbose:
        print("U_X initial/final line:", ux_label_line)

    if return_cnot_steps:
        return {
            "unitary": "U_X",
            "label_lines": label_lines,
            "coord_lines": coord_lines,
            "step_moves": [],
            "cnot_steps_by_update": [],
            "cnot_gates_by_update": [],
            "grid": up_spanning_data["grid"],
            "faces": up_spanning_data["faces"],
        }

    if return_coords:
        return label_lines, coord_lines

    return label_lines