from Scripts.Compiler import (
    operation_physical_qubit,
    cnot_depth,
    single_qubit_depth,
    total_greedy_depth,
)

from Scripts.QAOA_spanning_lines import (
    generate_qaoa_up_lhz_spanning_lines,
    generate_qaoa_ux_lhz_spanning_lines,
)


def compile_qaoa_up_with_lhz_spanning_lines(
    operations,
    n,
    spanning_data=None,
    verbose=False,
    return_debug=False,
):
    """
    Compile the QAOA problem unitary U_P using the LHZ U_P spanning-line
    schedule.

    The problem unitary is

        U_P(gamma) = exp(i gamma H_P),

    with

        H_P = sum_{j<k} J_jk Z_j Z_k + sum_j h_j Z_j.

    The input operation list is assumed to contain only logical RZ rotations:

        ["RZ", [j], theta]
        ["RZ", [j, k], theta]

    Since all Z-type rotations commute, the compiler applies a rotation as soon
    as its corresponding logical parity label appears on the current spanning
    line. Between consecutive spanning lines, the CNOTs generated by the U_P
    spanning-line schedule are inserted.

    Parameters
    ----------
    operations : list[list]
        Logical U_P operation list.

    n : int
        Number of logical qubits.

    spanning_data : dict or None
        Optional output of

            generate_qaoa_up_lhz_spanning_lines(
                n,
                return_cnot_steps=True,
            )

        If None, it is generated automatically.

    verbose : bool
        If True, print placement and spanning-line transition information.

    return_debug : bool
        If True, return a debug dictionary.

    Returns
    -------
    compiled_ops : list[list]
        Physical operation list in the format

            ["RZ", [physical_qubit], theta]
            ["CNOT", [control, target], "N/A"]

    debug : dict, optional
        Returned only if return_debug=True.
    """
    if spanning_data is None:
        spanning_data = generate_qaoa_up_lhz_spanning_lines(
            n,
            return_cnot_steps=True,
            verbose=False,
        )

    label_lines = spanning_data["label_lines"]
    cnot_gates_by_update = spanning_data["cnot_gates_by_update"]

    if len(label_lines) == 0:
        raise ValueError("No U_P spanning lines were generated.")

    remaining_ops = [list(op) for op in operations]

    for op in remaining_ops:
        if op[0].upper() != "RZ":
            raise ValueError(
                "compile_qaoa_up_with_lhz_spanning_lines only supports RZ "
                f"operations. Got {op}."
            )

    compiled_ops = []
    placement_log = []

    line_index = 0
    current_line = label_lines[line_index]

    while remaining_ops:
        placed_any = True

        while placed_any:
            placed_any = False

            for op_index, operation in enumerate(list(remaining_ops)):
                physical_qubit = operation_physical_qubit(operation, current_line)

                if physical_qubit is None:
                    continue

                logical_op = remaining_ops.pop(op_index)
                gate_type, logical_wires, angle = logical_op
                gate_type = gate_type.upper()

                physical_op = [gate_type, [physical_qubit], angle]
                compiled_ops.append(physical_op)

                placement_log.append(
                    {
                        "logical_operation": logical_op,
                        "physical_operation": physical_op,
                        "spanning_line_index": line_index,
                        "spanning_line": current_line,
                        "moved_across_previous_ops": True,
                        "remaining_index": op_index,
                    }
                )

                if verbose:
                    print(
                        f"Placed {logical_op} on U_P line {line_index} "
                        f"{current_line} as {physical_op}"
                    )

                placed_any = True
                break

        if not remaining_ops:
            break

        if line_index >= len(label_lines) - 1:
            raise RuntimeError(
                "Reached the end of the U_P spanning-line schedule before all "
                "RZ rotations could be made local.\n"
                f"Remaining operations:\n"
                + "\n".join(str(op) for op in remaining_ops)
                + f"\nCurrent line: {current_line}\n"
                + f"Line index:   {line_index}"
            )

        transition_cnots = cnot_gates_by_update[line_index]
        compiled_ops.extend(transition_cnots)

        if verbose:
            print(
                f"Moved U_P spanning line {line_index} -> {line_index + 1}: "
                f"{label_lines[line_index]} -> {label_lines[line_index + 1]}"
            )
            for cnot in transition_cnots:
                print("   ", cnot)

        line_index += 1
        current_line = label_lines[line_index]

    if return_debug:
        return compiled_ops, {
            "unitary": "U_P",
            "spanning_data": spanning_data,
            "placement_log": placement_log,
            "final_line_index": line_index,
            "final_spanning_line": current_line,
            "cnot_count": sum(1 for op in compiled_ops if op[0].upper() == "CNOT"),
            "rotation_count": sum(
                1 for op in compiled_ops if op[0].upper() in ("H", "RX", "RZ")
            ),
            "cnot_depth": cnot_depth(compiled_ops),
            "single_qubit_depth": single_qubit_depth(compiled_ops),
            "total_greedy_depth": total_greedy_depth(compiled_ops),
        }

    return compiled_ops

def compile_qaoa_ux_with_lhz_spanning_lines(
    operations,
    n,
    ux_spanning_data=None,
    up_spanning_data=None,
    verbose=False,
    return_debug=False,
):
    """
    Compile the QAOA mixer unitary U_X using the LHZ X-line construction.

    The mixer unitary is

        U_X(beta) = exp(i beta sum_j X_j).

    This compiler assumes that U_X starts from the final spanning line of the
    U_P schedule. The intermediate X-line movements do not follow the standard
    right-moving extended-LHZ spanning-line sweep. Instead, they use the
    constant-depth X-line construction.

    The physical pattern is:

      1. Apply CNOTs on pairs

             1 -> 0, 3 -> 2, 5 -> 4, ...

      2. Apply RX on physical qubits

             1, 3, 5, ...

         and also on the final physical qubit if n is odd.

      3. Undo the first CNOT layer.

      4. Apply CNOTs on pairs

             2 -> 1, 4 -> 3, 6 -> 5, ...

      5. Apply RX on physical qubits

             0, 2, 4, ...

         excluding the final physical qubit if it was already treated in step 2.

      6. Undo the second CNOT layer.

    For n=5, using zero-indexed physical qubits, this gives

        CNOT 3 -> 2
        CNOT 1 -> 0
        RX on 4
        RX on 3
        RX on 1
        CNOT 3 -> 2
        CNOT 1 -> 0
        CNOT 2 -> 1
        RX on 2
        RX on 0
        CNOT 2 -> 1

    This is the zero-indexed version of the one-indexed description

        CNOT 4 -> 3
        CNOT 2 -> 1
        RX on qubits 5, 4, 2
        CNOT 4 -> 3
        CNOT 2 -> 1
        CNOT 3 -> 2
        RX on qubits 3, 1
        CNOT 3 -> 2

    Parameters
    ----------
    operations : list[list]
        Logical U_X operation list. Expected format:

            ["RX", [j], beta]

        for j = 0, ..., n-1. The compiler assumes all angles are equal.

    n : int
        Number of logical qubits.

    ux_spanning_data : dict or None
        Optional output of

            generate_qaoa_ux_lhz_spanning_lines(
                n,
                return_cnot_steps=True,
            )

    up_spanning_data : dict or None
        Optional U_P spanning data. Used only if ux_spanning_data is None.

    verbose : bool
        If True, print placement information.

    return_debug : bool
        If True, return a debug dictionary.

    Returns
    -------
    compiled_ops : list[list]
        Physical operation list containing RX gates and CNOTs.

    debug : dict, optional
        Returned only if return_debug=True.
    """
    if n < 2:
        raise ValueError("n must be at least 2.")

    if ux_spanning_data is None:
        ux_spanning_data = generate_qaoa_ux_lhz_spanning_lines(
            n,
            up_spanning_data=up_spanning_data,
            return_cnot_steps=True,
            verbose=False,
        )

    label_lines = ux_spanning_data["label_lines"]

    if len(label_lines) != 1:
        raise ValueError(
            "The U_X spanning data should contain exactly one initial/final line."
        )

    current_line = label_lines[0]

    rx_ops = [list(op) for op in operations]

    for op in rx_ops:
        if op[0].upper() != "RX":
            raise ValueError(
                "compile_qaoa_ux_with_lhz_spanning_lines only supports RX "
                f"operations. Got {op}."
            )

    if len(rx_ops) != n:
        raise ValueError(
            f"Expected {n} RX operations for U_X, got {len(rx_ops)}."
        )

    angles = [op[2] for op in rx_ops]

    if len(set(angles)) != 1:
        raise ValueError(
            "This U_X compiler assumes a single common beta angle for all RX gates."
        )

    beta = angles[0]

    compiled_ops = []
    placement_log = []

    def append_cnot(control, target, stage):
        op = ["CNOT", [control, target], "N/A"]
        compiled_ops.append(op)

        if verbose:
            print(f"{stage}: {op}")

    def append_rx(physical_qubit, stage):
        op = ["RX", [physical_qubit], beta]
        compiled_ops.append(op)

        placement_log.append(
            {
                "logical_operation": ["RX", ["X-line"], beta],
                "physical_operation": op,
                "spanning_line_index": 0,
                "spanning_line": current_line,
                "moved_across_previous_ops": False,
                "remaining_index": None,
                "stage": stage,
            }
        )

        if verbose:
            print(f"{stage}: {op}")

    # First CNOT layer: odd physical qubits control the previous even qubit.
    first_layer = [(control, control - 1) for control in range(1, n, 2)]

    # Second CNOT layer: even physical qubits control the previous odd qubit.
    # If n is odd, the final physical qubit was already used as a boundary RX
    # site in the first RX layer, so it is excluded.
    second_layer = [
        (control, control - 1)
        for control in range(2, n, 2)
        if not (n % 2 == 1 and control == n - 1)
    ]

    # RX sites after first CNOT layer.
    first_rx_sites = list(range(1, n, 2))
    if n % 2 == 1:
        first_rx_sites.append(n - 1)

    # RX sites after second CNOT layer.
    second_rx_sites = list(range(0, n, 2))
    if n % 2 == 1 and (n - 1) in second_rx_sites:
        second_rx_sites.remove(n - 1)

    # To match the example, apply the disjoint CNOTs from right to left.
    for control, target in reversed(first_layer):
        append_cnot(control, target, "U_X first CNOT layer")

    # Also match the example by applying RXs from right to left.
    for q in sorted(first_rx_sites, reverse=True):
        append_rx(q, "U_X first RX layer")

    # Undo first CNOT layer.
    for control, target in reversed(first_layer):
        append_cnot(control, target, "U_X undo first CNOT layer")

    # Second CNOT layer.
    for control, target in reversed(second_layer):
        append_cnot(control, target, "U_X second CNOT layer")

    # Second RX layer.
    for q in sorted(second_rx_sites, reverse=True):
        append_rx(q, "U_X second RX layer")

    # Undo second CNOT layer.
    for control, target in reversed(second_layer):
        append_cnot(control, target, "U_X undo second CNOT layer")

    if return_debug:
        return compiled_ops, {
            "unitary": "U_X",
            "spanning_data": ux_spanning_data,
            "placement_log": placement_log,
            "final_line_index": 0,
            "final_spanning_line": current_line,
            "cnot_count": sum(1 for op in compiled_ops if op[0].upper() == "CNOT"),
            "rotation_count": sum(
                1 for op in compiled_ops if op[0].upper() in ("H", "RX", "RZ")
            ),
            "cnot_depth": cnot_depth(compiled_ops),
            "single_qubit_depth": single_qubit_depth(compiled_ops),
            "total_greedy_depth": total_greedy_depth(compiled_ops),
        }

    return compiled_ops